export * from "./WelcomeScreen"
export * from "./ErrorScreen/ErrorBoundary"
// export other screens here
export * from "./HomeScreen"
export * from "./ManagementScreen"
export * from "./ClassroomListScreen"
export * from "./CreateClassroomScreen"
export * from "./StudentListScreen"
export * from "./CourseListScreen"
export * from "./CreateCourseScreen"
export * from "./CreateStudentScreen"
export * from "./CreateTimetableScreen"
export * from "./CourseAttendanceScreen"
export * from "./AttendanceListScreen"
